# Task
Import an open-source model to fetch the latest news with details and pictures.

## Research and select a suitable model

### Subtask:
Identify open-source models that can fetch news articles and potentially extract relevant information and media. This might involve exploring libraries or models related to web scraping, information extraction, or natural language processing.

## Set up the model environment

### Subtask:
Install the chosen model and any necessary dependencies in the Colab environment. This may involve using pip to install libraries.

**Reasoning**:
Install the identified open-source library for fetching news articles using pip.

In [ ]:
%pip install newspaper3k

Requirement already satisfied: newspaper3k in /usr/local/lib/python3.12/dist-packages (0.2.8)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (4.13.5)
Requirement already satisfied: Pillow>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (11.3.0)
Requirement already satisfied: PyYAML>=3.11 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.2)
Requirement already satisfied: cssselect>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (1.3.0)
Requirement already satisfied: lxml>=3.6.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (5.4.0)
Requirement already satisfied: nltk>=3.2.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (3.9.1)
Requirement already satisfied: requests>=2.10.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (2.32.4)
Requirement already satisfied: feedparser>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.11)
Requirement already satisfied: tldextract>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (5.3.0)
Requirement already satisfied: feedfinder2>=0.0.4 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.0.4)
Requirement already satisfied: jieba3k>=0.35.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.35.1)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (2.9.0.post0)
Requirement already satisfied: tinysegmenter==0.3 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->newspaper3k) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->newspaper3k) (4.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from feedfinder2>=0.0.4->newspaper3k) (1.17.0)
Requirement already satisfied: sgmllib3k in /usr/local/lib/python3.12/dist-packages (from feedparser>=5.2.1->newspaper3k) (1.0.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (2025.8.3)
Requirement already satisfied: requests-file>=1.4 in /usr/local/lib/python3.12/dist-packages (from tldextract>=2.0.1->newspaper3k) (2.1.0)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.12/dist-packages (from tldextract>=2.0.1->newspaper3k) (3.19.1)

**Reasoning**:
Confirm the installation of the newspaper3k library by attempting to import it.

**Reasoning**:
The import failed because of a missing dependency, as indicated by the traceback. Install the missing dependency using pip.

In [ ]:
%pip install lxml_html_clean

Requirement already satisfied: lxml_html_clean in /usr/local/lib/python3.12/dist-packages (0.4.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from lxml_html_clean) (5.4.0)

**Reasoning**:
Attempt to import the newspaper library again after installing the missing dependency to confirm successful installation.

In [ ]:
import newspaper
print("newspaper3k imported successfully!")

newspaper3k imported successfully!

## Fetch news data

### Subtask:
Write code to use the selected model or library to fetch news articles from a source. This could involve specifying keywords, sources, or dates.

**Reasoning**:
The instructions require using the newspaper library to fetch news articles from a source URL, and the next step is to write the code to do that.

In [ ]:
from newspaper import build

# url = 'https://www.wired.com/'
# url = 'https://www.technologyreview.com/'
url = 'https://www.sciencefocus.com/'

paper = build(url, memoize_articles=False)
articles = paper.articles

print(f"Successfully fetched {len(articles)} articles from {url}")

if articles:
    # Print details of the first article as an example
    first_article = articles[0]
    first_article.download()
    first_article.parse()
    print("\nDetails of the first article:")
    print(f"Title: {first_article.title}")
    print(f"Authors: {first_article.authors}")
    print(f"Publish Date: {first_article.publish_date}")
    print(f"Summary: {first_article.text[:200]}...")  # first 200 chars of article text
    print(f"Image URL: {first_article.top_image}")
else:
    print("No articles found.")

CRITICAL:newspaper.network:[REQUEST FAILED] 404 Client Error: Not Found for url: https://www.sciencefocus.com/feed
CRITICAL:newspaper.network:[REQUEST FAILED] 404 Client Error: Not Found for url: https://www.sciencefocus.com/feeds
CRITICAL:newspaper.network:[REQUEST FAILED] 404 Client Error: Not Found for url: https://www.sciencefocus.com/rss

Successfully fetched 98 articles from https://www.sciencefocus.com/

Details of the first article:
Title: We may have solved a major part of the puzzle of how life got started
Authors: ['Tom.Howarth Ourmedia.Co.Uk', 'Tom Is Trends Editor At']
Publish Date: 2025-08-27 15:00:00+00:00
Summary: Scientists have taken a major step towards solving one of biology’s deepest mysteries: how two pieces of life’s essential molecules first came together more than four billion years ago.

Proteins, con...
Image URL: https://c02.purpledshub.com/uploads/sites/41/2025/08/Earth.jpg?w=1200

## Extract details and media

### Subtask:
Process the fetched news data to extract details like the headline, body, publication date, and potentially links to images or other media.

**Reasoning**:
Iterate through the list of articles, download and parse each one if necessary, extract the required details (title, text, publish date, top image), and store them in a list of dictionaries.

In [ ]:
valid_articles = [
    a for a in articles
    if all(x not in a.url for x in ["/rss", "/feed", "/video", "/offers", "/tag/"])
]

news_data = []
for article in valid_articles:
    try:
        article.download()
        article.parse()
        news_data.append({
            'title': article.title,
            'body': article.text,
            'publish_date': article.publish_date,
            'image_url': article.top_image
        })
    except Exception as e:
        print(f"Skipping {article.url}: {e}")
        continue

import pandas as pd
news_df = pd.DataFrame(news_data)
display(news_df.head())
print(f"\nSuccessfully processed {len(news_df)} articles.")

,title,body,publish_date,image_url
0,We may have solved a major part of the puzzle ...,Scientists have taken a major step towards sol...,2025-08-27 15:00:00+00:00,https://c02.purpledshub.com/uploads/sites/41/2...
1,How we read emotions could reveal a hidden sig...,"As we get older, we may be more inclined to th...",2025-08-26 17:00:00+00:00,https://c02.purpledshub.com/uploads/sites/41/2...
2,Ocean water is now corroding shark teeth at al...,The rising acidity of Earth’s oceans is causin...,2025-08-27 09:00:00+00:00,https://c02.purpledshub.com/uploads/sites/41/2...
3,Cats get dementia too. And they might be the k...,Cats who develop dementia-like symptoms in old...,2025-08-23 09:00:00+00:00,https://c02.purpledshub.com/uploads/sites/41/2...
4,New issue: The galaxies that shouldn't exist,Fit at 40 (and beyond)\n\nThink you're too old...,2025-08-19 07:00:00+00:00,https://c02.purpledshub.com/uploads/sites/41/2...

Successfully processed 97 articles.

**Reasoning**:
The previous attempt failed because the `Article` object does not have `is_downloaded` or `is_parsed` attributes. I need to remove the checks and directly call download and parse on each article within the loop.

In [ ]:
import pandas as pd
import re # Import the re module for regular expressions

news_data = []

# Define keywords for desired topics (case-insensitive)
innovation_keywords = ['innovation', 'cutting edge', 'breakthrough', 'new technology', 'research', 'discovery', 'invention']
health_keywords = ['genetic disease', 'rare disease', 'health', 'medical', 'syndrome', 'condition', 'cure', 'therapy', 'patient']
captivating_keywords = ['mystery', 'unusual', 'strange', 'shocking', 'remarkable', 'extraordinary', 'captivating', 'unexplained', 'rare incident']
exclude_keywords = ['political', 'geopolitical', 'finance', 'economy', 'market', 'business', 'election', 'government', 'conflict', 'war']

def contains_keywords(text, keywords):
    """Checks if text contains any of the keywords."""
    if not isinstance(text, str):
        return False
    text = text.lower()
    for keyword in keywords:
        if re.search(r'\b' + re.escape(keyword) + r'\b', text):
            return True
    return False

def contains_exclude_keywords(text, keywords):
    """Checks if text contains any of the exclusion keywords."""
    if not isinstance(text, str):
        return False
    text = text.lower()
    for keyword in keywords:
        if re.search(r'\b' + re.escape(keyword) + r'\b', text):
            return True
    return False


for article in articles:
    try:
        # Directly download and parse the article
        article.download()
        article.parse()

        # Extract details
        title = article.title
        body = article.text
        publish_date = article.publish_date
        image_url = article.top_image

        # Filter articles based on keywords
        is_innovative = contains_keywords(title, innovation_keywords) or contains_keywords(body, innovation_keywords)
        is_health_related = contains_keywords(title, health_keywords) or contains_keywords(body, health_keywords)
        is_captivating = contains_keywords(title, captivating_keywords) or contains_keywords(body, captivating_keywords)
        is_excluded = contains_exclude_keywords(title, exclude_keywords) or contains_exclude_keywords(body, exclude_keywords)

        if (is_innovative or is_health_related or is_captivating) and not is_excluded:
             # Store the extracted information
            news_data.append({
                'title': title,
                'body': body,
                'publish_date': publish_date,
                'image_url': image_url
            })

    except Exception as e:
        # Catch exceptions during download or parse and skip the article
        print(f"Could not process article: {e}")
        continue

# Convert the list of dictionaries to a DataFrame for easier handling and display
news_df = pd.DataFrame(news_data)

# Display the first few rows of the DataFrame
display(news_df.head())

# Print the total number of articles processed
print(f"\nSuccessfully processed {len(news_df)} articles based on your preferences.")

,title,body,publish_date,image_url
0,We may have solved a major part of the puzzle ...,Scientists have taken a major step towards sol...,2025-08-27 15:00:00+00:00,https://c02.purpledshub.com/uploads/sites/41/2...
1,How we read emotions could reveal a hidden sig...,"As we get older, we may be more inclined to th...",2025-08-26 17:00:00+00:00,https://c02.purpledshub.com/uploads/sites/41/2...
2,Ocean water is now corroding shark teeth at al...,The rising acidity of Earth’s oceans is causin...,2025-08-27 09:00:00+00:00,https://c02.purpledshub.com/uploads/sites/41/2...
3,Cats get dementia too. And they might be the k...,Cats who develop dementia-like symptoms in old...,2025-08-23 09:00:00+00:00,https://c02.purpledshub.com/uploads/sites/41/2...
4,New issue: The galaxies that shouldn't exist,Fit at 40 (and beyond)\n\nThink you're too old...,2025-08-19 07:00:00+00:00,https://c02.purpledshub.com/uploads/sites/41/2...

Successfully processed 61 articles based on your preferences.

## Display the news

### Subtask:
Present the extracted news information to the user, including the details and any available pictures.

**Reasoning**:
Iterate through the dataframe, extract the details, and print them along with the image if available.

In [ ]:
%pip install validators

Requirement already satisfied: validators in /usr/local/lib/python3.12/dist-packages (0.35.0)

**Reasoning**:
Now that the 'validators' module is installed, retry iterating through the dataframe, extracting the details, and printing them along with the image if available.

In [ ]:
from IPython.display import display, Image
import validators

# Iterate through the rows of the news_df DataFrame
for index, row in news_df.iterrows():
    title = row['title']
    body = row['body']
    publish_date = row['publish_date']
    image_url = row['image_url']

    print(f"Title: {title}")
    if pd.notna(publish_date):
        print(f"Publish Date: {publish_date.strftime('%Y-%m-%d')}")
    else:
        print("Publish Date: N/A")
    print(f"Body Snippet: {body[:200]}...\n")

    # Display the image if the URL exists and is valid
    if pd.notna(image_url) and validators.url(image_url):
        try:
            display(Image(url=image_url, width=300))
        except Exception as e:
            print(f"Could not display image from URL {image_url}: {e}")
    else:
        print("Image: Not available or invalid URL\n")

    print("-" * 50) # Separator for clarity

Title: We may have solved a major part of the puzzle of how life got started
Publish Date: 2025-08-27
Body Snippet: Scientists have taken a major step towards solving one of biology’s deepest mysteries: how two pieces of life’s essential molecules first came together more than four billion years ago.

Proteins, con...

--------------------------------------------------
Title: How we read emotions could reveal a hidden sign of brain ageing
Publish Date: 2025-08-26
Body Snippet: As we get older, we may be more inclined to think people look happy, a new study has found.

Scientists have found that ageing adults often show a 'positivity bias' when interpreting facial expression...

--------------------------------------------------
Title: Ocean water is now corroding shark teeth at alarming rate, study finds
Publish Date: 2025-08-27
Body Snippet: The rising acidity of Earth’s oceans is causing shark teeth to corrode and waste away.

As top predators, a shark’s teeth are its most important tool, but a new study has found that climate change is ...

--------------------------------------------------
Title: Cats get dementia too. And they might be the key to new human treatments
Publish Date: 2025-08-23
Body Snippet: Cats who develop dementia-like symptoms in old age have similar changes in their brain to humans with Alzheimer’s, a new study has found. The findings could kick down the door to new research, possibl...

--------------------------------------------------
Title: New issue: The galaxies that shouldn't exist
Publish Date: 2025-08-19
Body Snippet: Fit at 40 (and beyond)

Think you're too old to get into shape? Think again. We've pulled together the best exercises you can do once you've levelled up past 40.

Find your purpose

We all need a rais...

--------------------------------------------------
Title: Hidden belly fat could be ageing your heart – even if you have a healthy weight
Publish Date: 2025-08-22
Body Snippet: A new study has found that visceral fat – the hidden belly fat stored deep in the abdomen – can accelerate the ageing of your heart.

Unlike subcutaneous fat, which sits just below the skin, visceral ...

--------------------------------------------------
Title: There's a new type of acid rain – and scientists are worried
Publish Date: 2025-08-15
Body Snippet: Scientists have warned about a new kind of acid rain that is everywhere, is almost impossible to clean up, and could be a threat to every living thing on planet Earth.

Trifluoroacetic acid (TFA) – a ...

--------------------------------------------------
Title: This tiny stone tool may have just rewritten human history
Publish Date: 2025-08-14
Body Snippet: A discovery on the Indonesian island of Sulawesi has pushed back the timeline of early human sea crossings and deepened the mystery of who made them.

Archaeologists have unearthed stone tools at a si...

--------------------------------------------------
Title: Top 10 worst inventions ever created
Publish Date: 2025-08-16
Body Snippet: Look around your home and you'll see countless amazing inventions that have all made our lives easier – you are reading this on one right now.

However, not all inventions are well thought-out and use...

--------------------------------------------------
Title: Instant Genius Podcast: Why you’re not actually addicted to your phone
Publish Date: 2024-03-18
Body Snippet: Just about everywhere we look today, screens, and in particular social media, are being called addictive, and being blamed for causing mental health problems and damaging childhood development.

But d...

--------------------------------------------------
Title: 'Zero-calorie' foods won't help you lose weight. This will
Publish Date: 2025-07-06
Body Snippet: Negative-calorie or zero-calorie foods are controversial despite their popularity on diet websites. The idea is that our bodies use as much (or more) energy to digest a chosen fruit or vegetable as th...

--------------------------------------------------
Title: From 9/11 to Hurricane Katrina: 15 unforgettable photos of Earth from space
Publish Date: 2025-06-14
Body Snippet: It may not be a household name like the Hubble Space Telescope or the James Webb Space Telescope, but NASA’s Landsat 7 has quietly transformed how we see our planet. For more than 25 years, it’s captu...

--------------------------------------------------
Title: The 15 weirdest pictures of nature's smallest animals
Publish Date: 2025-02-05
Body Snippet: Not an insect fan? Look away now: the winning images in the Royal Entomological Society’s Photography Competition 2024 have just been announced.

This year's selection of close-up critters features a ...

--------------------------------------------------
Title: 5 illusions that reveal how your brain warps reality
Publish Date: 2025-08-10
Body Snippet: As you scroll through this article, your brain is hard at work creating the mental world you live in. You probably have a seamless sense that you’re embedded in a world full of other people, objects, ...

--------------------------------------------------
Title: After decades of guesswork, science might have found a real hangover hack
Publish Date: 2025-07-27
Body Snippet: You don't need a scientist to tell you that hangovers are bad. Too much alcohol often leads to headaches, nausea and fatigue, and a body-wide wave of inflammation.

This, of course, is to say nothing ...

--------------------------------------------------
Title: Here's the most effective, proven way to shape your microbiome for slower ageing
Publish Date: 2025-07-26
Body Snippet: Take a stroll through the supermarket and you'll find plenty of products stuffed with 'friendly bacteria.' Bacteria – the good guys! Chug them down and they’ll help to look after you.

We're used to t...

--------------------------------------------------
Title: I was sceptical of self-hypnosis – until it started working…
Publish Date: 2025-07-16
Body Snippet: I'm sitting with my back straight, my eyes closed and my iPad resting on my lap. "Let one hand float up in the air as if it were a balloon," a soothing voice tells me from the speakers, and I do as it...

--------------------------------------------------
Title: I'm a psychologist. Here's what we keep getting wrong about ADHD
Publish Date: 2025-07-03
Body Snippet: These days, more and more youngsters are turning to social media platforms such as TikTok for advice on everything from how to perform the latest K-pop dance moves to hacks on producing the perfect wi...

--------------------------------------------------
Title: Here’s how narcissism shapes a person’s social media habits, study reveals
Publish Date: 2025-06-30
Body Snippet: Narcissists are more likely to be addicted to social media, according to new research.

The study, conducted by researchers from the University of Gdańsk, Poland, suggests that several, but not all, s...

--------------------------------------------------
Title: 4 foods that boost Ozempic weight loss (and the ones that slow it)
Publish Date: 2025-06-29
Body Snippet: When taking Ozempic (semaglutide), a medication prescribed for managing type 2 diabetes and sometimes used for weight loss, there are no specific foods that are off limits.

But ultimately, to make th...

--------------------------------------------------
Title: How to avoid 'Ozempic face', according to a doctor
Publish Date: 2025-06-26
Body Snippet: Although they were originally developed to treat diabetes, the rise of drugs like Ozempic has sparked a weight-loss revolution.

While growing in popularity to help people with a high body mass index,...

--------------------------------------------------
Title: Here’s how to tell if your dog actually loves you, according to science
Publish Date: 2025-08-27
Body Snippet: You won’t find the word ‘love’ in the published papers of scientists who research non-human animals. Ironically, though, most animal behaviour scientists were drawn to the subject because of their dee...

--------------------------------------------------
Title: Is the honeybee crisis a hoax after all?
Publish Date: 2025-07-31
Body Snippet: When I started studying honeybees in 1998, I quickly noticed just how much people loved them. I also realised that people’s knowledge rarely extended beyond “bees make honey” and “they live in hives”....

--------------------------------------------------
Title: These are the dog breeds most at risk of overeating, says study
Publish Date: 2025-07-30
Body Snippet: When it comes to pooch plumpness, some dog breeds are more likely to be overweight than others, according to a recent study.

Researchers at Texas A&M University measured ‘food motivation’ by surveyin...

--------------------------------------------------
Title: This (very cute) footage shows baby turtles being called by their mothers
Publish Date: 2025-07-28
Body Snippet: Emerging from the darkness, a slimy claw punches through a gooey membrane and stretches towards the light. Thunder rumbles and crackles above the ground.

This isn’t the undead waking from their grave...

--------------------------------------------------
Title: This cat-borne parasite could be causing you to make bad decisions. Here's how
Publish Date: 2025-07-25
Body Snippet: A parasite spread by cats may be manipulating half of the world's population's brains, causing them to take more risks and behave more aggressively.

A new review article brought together multiple stu...

--------------------------------------------------
Title: Here's what your dog's TV watching habits say about their personality
Publish Date: 2025-07-17
Body Snippet: How your dog reacts to your favourite TV show could say a lot about their personality, according to the latest research.

With the help of hundreds of dogs, a recent Nature study found that excitable ...

--------------------------------------------------
Title: This bizarre underwater 'blue dragon' fights with stolen jellyfish venom
Publish Date: 2025-07-15
Body Snippet: Far from the shore, out in the vast expanses of the open seas lives a group of unusual animals, collectively known as ‘neuston’.

Their home is the giant, two-dimensional skin of the sea, which forms ...

--------------------------------------------------
Title: This 'explosive' squirting cucumber can launch seeds at nearly 30mph
Publish Date: 2025-07-08
Body Snippet: Scientists have discovered the explosive secret behind one of nature's most dramatic seed dispersal methods: the squirting cucumbers.

The plant, Ecballium elaterium, lives up to its name by firing it...

--------------------------------------------------
Title: Scientists uncover (very) creepy reason humans first kept pet cats
Publish Date: 2025-07-07
Body Snippet: Editor's note 21 August 2025: one of the research papers mentioned in this article has now been withdrawn while the authors re-examine their results.

Two new studies have uncovered fresh clues about ...

--------------------------------------------------
Title: We can't predict when a mega-tsunami will strike. Here's why
Publish Date: 2025-08-23
Body Snippet: On 30 July at 12:25am BST (11:25am local time), a massive earthquake struck just off the coast of the Kamchatka Peninsula, Russia. With a magnitude of 8.8, the event was the sixth-largest earthquake i...

--------------------------------------------------
Title: A massive earthquake could be brewing beneath North America, study suggests
Publish Date: 2025-08-09
Body Snippet: A hidden tectonic fault in Canada’s Yukon could be gearing up to unleash a major earthquake of at least magnitude 7.5, according to a new study.

The Tintina fault, which runs from northeastern Britis...

--------------------------------------------------
Title: Reducing pollution may have unmasked deeper climate risks, study reveals
Publish Date: 2025-07-19
Body Snippet: Cleaning up the air we breathe may be a win for public health, but it also speeds up global warming. That’s according to a recent study published in Communications Earth & Environment, which linked th...

--------------------------------------------------
Title: Mysterious 'surge' under Earth crust could reshape world map, study claims
Publish Date: 2025-07-06
Body Snippet: A heartbeat-like pulse has been discovered beating deep beneath East Africa – and it's ripping the continent apart.

The strange thumping is caused by a rhythmic surge of molten mantle rock rising and...

--------------------------------------------------
Title: Scientists have found what sounds eerily like Atlantis off Australia’s coast
Publish Date: 2025-06-28
Body Snippet: In the works of Plato, a Greek philosopher who lived around 2,400 years ago, the island of Atlantis was said to have been drowned in the Atlantic Ocean after the hubris of its people angered the Gods....

--------------------------------------------------
Title: Can humans live under the sea? This live experiment plans to find out
Publish Date: 2025-06-15
Body Snippet: Whether it's to escape environmental collapse or to explore new, unknown territories, the drive to establish human colonies in places other than on Earth has been gaining momentum in recent years.

An...

--------------------------------------------------
Title: Why your knees ache more with age – and how to loosen them up
Publish Date: 2025-07-12
Body Snippet: Atrophy comes for pretty much every part of our bodies, but the effects of time are particularly rough on the knees. Why? Because they’re complicated anatomical machines with a number of moving parts,...

--------------------------------------------------
Title: Some receipts are coated in 'forever chemicals'. Here's what that means
Publish Date: 2025-06-30
Body Snippet: Some so-called 'thermal' till receipts contain bisphenols (including BPA and BPS) as a result of the way they're printed. In the UK, BPA receipts are banned, but BPS receipts are not.

A 2023 estimate...

--------------------------------------------------
Title: This bold theory says the Big Bang wasn't our beginning
Publish Date: 2025-06-28
Body Snippet: What is the ekpyrotic Universe theory? Ekpyrotic cosmology is an alternative theory to the standard theory of cosmology, which is known as the Lambda-CDM, or ΛCDM model.

In the ΛCDM model, the remark...

--------------------------------------------------
Title: The hidden ways a narcissist tries to manipulate your personality
Publish Date: 2025-06-26
Body Snippet: Are you an empathic people-pleaser who prefers to stay out of the spotlight? Do you listen to others, but struggle to express your own thoughts and feelings? Did you grow up around, or are you in a lo...

--------------------------------------------------
Title: Suspended animation is here. Just not how you'd expect
Publish Date: 2025-06-23
Body Snippet: Will suspended animation ever exist? It already does, if you count animals hibernating over winter. But if you mean the sort of suspended animation depicted in science fiction (where a person is place...

--------------------------------------------------
Title: This 80-million-year-old shark species is a biological mystery
Publish Date: 2025-06-22
Body Snippet: In the dark waters of the deep sea, lurk many curious and enigmatic animals that few have seen. Frilled sharks (Chlamydoselachus anguineus), for instance, have been known about for more than a century...

--------------------------------------------------
Title: This article is scientifically proven to improve your willpower
Publish Date: 2025-08-25
Body Snippet: We’ve all done it. After a few days of successfully exercising self-restraint, the stresses of work and daily life gets the better of us. Our willpower cracks and the chocolate cupboard gets raided. T...

--------------------------------------------------
Title: 10 simple ways to keep your dogs safe and happy during a heatwave
Publish Date: 2025-06-24
Body Snippet: With temperatures soaring across much of the northern hemisphere, it can be hard to find ways to keep yourself cool. Now imagine you were wearing a fur coat all day. Doesn’t sound too fun, does it?

W...

--------------------------------------------------
Title: The weirdest black hole in the Universe could be waking up
Publish Date: 2025-08-20
Body Snippet: Back in February 2024, astronomers witnessed something very strange happening in a galaxy 300 light-years away from Earth.

Erupting from the supermassive black hole located in its heart were huge fla...

--------------------------------------------------
Title: Something is wrong with our understanding of the Universe and the closer we look the weirder it gets
Publish Date: 2025-08-16
Body Snippet: "Cosmologists are often wrong, but never in doubt,” remarked the Russian Nobel Prize-winning physicist Lev Landau. Perhaps he had a point. Perhaps cosmologists should have a little more humility. Afte...

--------------------------------------------------
Title: This new experiment could take us closer to a theory of everything
Publish Date: 2025-07-21
Body Snippet: Humanity is one step closer to reaching an all-encompassing ‘theory of everything’ to explain the physical universe, thanks to a new paper published in PRX Quantum.

Three scientists in the US have de...

--------------------------------------------------
Title: The six little red dots that nearly broke the Universe
Publish Date: 2025-07-19
Body Snippet: The problems started with six little red dots. Six small fuzzy spots, among thousands of others, were enough to suddenly bring everything into question.

The dots appeared in images captured by the Ja...

--------------------------------------------------
Title: Astronomers have spotted a solar system being born for the first time
Publish Date: 2025-07-16
Body Snippet: For the first time, astronomers have caught a glimpse of a solar system just as it begins to form, spotting the first tiny seeds that will one day grow into planets taking shape around a distant baby ...

--------------------------------------------------
Title: We may finally have an easy way to make water on the Moon
Publish Date: 2025-07-16
Body Snippet: Scientists have developed a new technology that extracts water from Moon soil, offering a potential lifeline for future lunar explorers.

The findings, published in the journal Joule, could help reduc...

--------------------------------------------------
Title: Alien civilisations may be able to spy on us. Here's how
Publish Date: 2025-07-09
Body Snippet: The radio signals from our planet’s airports could be detected by alien astronomers even if their level of technology is the same as our own, according to an upcoming study.

Radar systems used to tra...

--------------------------------------------------
Title: Earth may be trapped inside a giant void in space, say scientists
Publish Date: 2025-07-09
Body Snippet: Earth and the rest of the Milky Way could be floating in a billion-light-year-wide cosmic void, according to new research.

By looking at the echoes left by the ‘soundwaves' of the Big Bang, a team of...

--------------------------------------------------
Title: This ‘impossible’ quantum discovery could rewrite the rules of existence
Publish Date: 2025-06-26
Body Snippet: It’s rare for anyone to claim that something physicists have believed for a century is wrong. But this is exactly what two physicists argue in a paper recently published in the prestigious science jou...

--------------------------------------------------
Title: These two signals are the closest we've come to alien contact
Publish Date: 2025-06-21
Body Snippet: In 2019, a radio telescope in Australia detected an interesting signal coming from the vicinity of Proxima Centauri, the closest star to Earth.

The signal, designated Breakthrough Listen Candidate 1 ...

--------------------------------------------------
Title: Here's what's (probably) on the other side of a black hole
Publish Date: 2025-06-01
Body Snippet: Perhaps the most surprising scientific discovery of the last decade is that the Universe is teeming with black holes.

They’ve been detected in a surprising variety of sizes: some with masses only a b...

--------------------------------------------------
Title: We’ve just found the largest black hole in the Universe (so far)
Publish Date: 2025-08-13
Body Snippet: Astronomers have tracked down the biggest black hole seen in the Universe so far.

Using two different types of measurement, astronomers recently discovered the behemoth of a black hole has almost 10,...

--------------------------------------------------
Title: Scientists are rethinking the cause of insomnia. Here's why
Publish Date: 2025-08-12
Body Snippet: Your gut microbes could be causing your insomnia, according to a new study from China. And the reverse is also true: your sleep habits could also impact your gut health.

Previous research has already...

--------------------------------------------------
Title: Human brains emit a seriously weird glow, study finds
Publish Date: 2025-08-08
Body Snippet: Our brains glow. We can’t see it happen with the naked eye, but scientists can measure extremely subtle light passing through the skull – and a recent study has found that this light changes depending...

--------------------------------------------------
Title: Scientists spent 25 years studying ‘super-agers’. Here’s what they learned
Publish Date: 2025-08-07
Body Snippet: After 25 years of research, scientists at Northwestern University, USA, have discovered why some adults can live well into their 80s and beyond with near-perfect cognition.

These ‘super-agers’, as th...

--------------------------------------------------
Title: New smart pill could let doctors explore and treat your gut from the inside
Publish Date: 2025-07-31
Body Snippet: A new technology could enable doctors to use microorganisms to diagnose and treat disease from inside the gut microbiome in future, according to a recent study.

Scientists genetically engineered bact...

--------------------------------------------------
Title: The deadly fungus behind Tutankhamun’s ‘curse’ could now save lives
Publish Date: 2025-07-31
Body Snippet: A fungus long blamed for the deaths of archaeologists who opened King Tutankhamun’s tomb may now help save lives. Researchers have harnessed the toxic fungus Aspergillus flavus – once linked to the so...

--------------------------------------------------

## Summary:

### Data Analysis Key Findings

*   The `newspaper3k` library was successfully installed and used to fetch 478 articles from the specified news source.
*   Details such as the article title, body text, publish date, and top image URL were extracted for the fetched articles.
*   The extracted news data, including title, body, publish date, and image URL, was successfully organized into a pandas DataFrame.
*   The extracted news information, including a text snippet and the associated image (if available and valid), was displayed for each article.
*   Some articles had missing publish dates or generic titles, indicating potential limitations in the extraction process for certain content.

### Insights or Next Steps

*   Consider adding error handling and logging to identify and troubleshoot issues with specific articles that fail to download or parse correctly.
*   Implement more robust validation and cleaning of extracted data, particularly for publish dates and titles, to ensure data quality.

## Summary:

### Data Analysis Key Findings

* The `newspaper3k` library was successfully installed and used to fetch 478 articles from the specified news source.
* Details such as the article title, body text, publish date, and top image URL were extracted for the fetched articles.
* The extracted news data, including title, body, publish date, and image URL, was successfully organized into a pandas DataFrame.
* The extracted news information, including a text snippet and the associated image (if available and valid), was displayed for each article.
* Some articles had missing publish dates or generic titles, indicating potential limitations in the extraction process for certain content.

### Insights or Next Steps

* Consider adding error handling and logging to identify and troubleshoot issues with specific articles that fail to download or parse correctly.
* Implement more robust validation and cleaning of extracted data, particularly for publish dates and titles, to ensure data quality.

In [ ]:
# Display the titles of the filtered news articles
print("Filtered News Titles:")
for index, row in news_df.iterrows():
    print(f"- {row['title']}")

Filtered News Titles:
- We may have solved a major part of the puzzle of how life got started
- How we read emotions could reveal a hidden sign of brain ageing
- Ocean water is now corroding shark teeth at alarming rate, study finds
- Cats get dementia too. And they might be the key to new human treatments
- New issue: The galaxies that shouldn't exist
- Hidden belly fat could be ageing your heart – even if you have a healthy weight
- There's a new type of acid rain – and scientists are worried
- This tiny stone tool may have just rewritten human history
- Top 10 worst inventions ever created
- Instant Genius Podcast: Why you’re not actually addicted to your phone
- 'Zero-calorie' foods won't help you lose weight. This will
- From 9/11 to Hurricane Katrina: 15 unforgettable photos of Earth from space
- The 15 weirdest pictures of nature's smallest animals
- 5 illusions that reveal how your brain warps reality
- After decades of guesswork, science might have found a real hangover hack
- Here's the most effective, proven way to shape your microbiome for slower ageing
- I was sceptical of self-hypnosis – until it started working…
- I'm a psychologist. Here's what we keep getting wrong about ADHD
- Here’s how narcissism shapes a person’s social media habits, study reveals
- 4 foods that boost Ozempic weight loss (and the ones that slow it)
- How to avoid 'Ozempic face', according to a doctor
- Here’s how to tell if your dog actually loves you, according to science
- Is the honeybee crisis a hoax after all?
- These are the dog breeds most at risk of overeating, says study
- This (very cute) footage shows baby turtles being called by their mothers
- This cat-borne parasite could be causing you to make bad decisions. Here's how
- Here's what your dog's TV watching habits say about their personality
- This bizarre underwater 'blue dragon' fights with stolen jellyfish venom
- This 'explosive' squirting cucumber can launch seeds at nearly 30mph
- Scientists uncover (very) creepy reason humans first kept pet cats
- We can't predict when a mega-tsunami will strike. Here's why
- A massive earthquake could be brewing beneath North America, study suggests
- Reducing pollution may have unmasked deeper climate risks, study reveals
- Mysterious 'surge' under Earth crust could reshape world map, study claims
- Scientists have found what sounds eerily like Atlantis off Australia’s coast
- Can humans live under the sea? This live experiment plans to find out
- Why your knees ache more with age – and how to loosen them up
- Some receipts are coated in 'forever chemicals'. Here's what that means
- This bold theory says the Big Bang wasn't our beginning
- The hidden ways a narcissist tries to manipulate your personality
- Suspended animation is here. Just not how you'd expect
- This 80-million-year-old shark species is a biological mystery
- This article is scientifically proven to improve your willpower
- 10 simple ways to keep your dogs safe and happy during a heatwave
- The weirdest black hole in the Universe could be waking up
- Something is wrong with our understanding of the Universe and the closer we look the weirder it gets
- This new experiment could take us closer to a theory of everything
- The six little red dots that nearly broke the Universe
- Astronomers have spotted a solar system being born for the first time
- We may finally have an easy way to make water on the Moon
- Alien civilisations may be able to spy on us. Here's how
- Earth may be trapped inside a giant void in space, say scientists
- This ‘impossible’ quantum discovery could rewrite the rules of existence
- These two signals are the closest we've come to alien contact
- Here's what's (probably) on the other side of a black hole
- We’ve just found the largest black hole in the Universe (so far)
- Scientists are rethinking the cause of insomnia. Here's why
- Human brains emit a seriously weird glow, study finds
- Scientists spent 25 years studying ‘super-agers’. Here’s what they learned
- New smart pill could let doctors explore and treat your gut from the inside
- The deadly fungus behind Tutankhamun’s ‘curse’ could now save lives

In [ ]:
# Save the DataFrame to a CSV file
news_df.to_csv('filtered_news.csv', index=False)

print("Filtered news data saved to 'filtered_news.csv'")

Filtered news data saved to 'filtered_news.csv'

In [ ]:
%pip install groq

Requirement already satisfied: groq in /usr/local/lib/python3.12/dist-packages (0.31.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq) (2.11.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (2025.8.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.1)

In [ ]:
import os
from groq import Groq

# Set your GROQ API key as an environment variable (recommended for security)
os.environ["GROQ_API_KEY"] = "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"

# Initialize the Groq client
client = Groq(
    api_key=os.environ.get("GROQ_API_KEY"),
)

In [ ]:
import pandas as pd
import re # Import the re module for regular expressions

def get_ranked_news(news_df, client, model="llama-3.1-8b-instant"):
    """
    Filter news for innovation/tech topics and rank them with Groq.
    Returns ranked results, the top headline, and the top narration.
    """
    # Step 1: Filter for interesting/captivating topics
    keywords = ["AI", "robot", "innovation", "tech", "discovery",
                "research", "launch", "breakthrough", "experiment", "science"]
    mask = news_df['title'].str.contains("|".join(keywords), case=False, na=False)
    filtered_df = news_df[mask] # Filter first

    if filtered_df.empty:
        return "No relevant news found.", None, None, None

    # Randomize the order of the filtered articles
    filtered_df = filtered_df.sample(frac=1).reset_index(drop=True).head(10) # then sample and take top 10

    # Step 2: Build a lightweight string with title + short description
    news_text = "\n".join(
        f"{i+1}. {row['title']} - {str(row.get('description',''))[:200]}"
        for i, row in filtered_df.iterrows()
    )

    # Step 3: Define the LLM prompt
    prompt = f"""
Analyze the following news articles and identify the best trending news
about technology, amazing facts, or innovations.
Rank the articles from 1 to N based on how captivating and interesting they are.
Exclude articles about politics, finance, or general business.

Here are the news articles:

{news_text}

Provide the output in this format:
Rank: [Rank Number]
Title: [Article Title]
Reasoning: [Brief explanation]

---
After the ranked list, also provide:

Headline: [Eye-catching headline for Rank 1]
Narration: [Captivating narration for Rank 1, suitable for a video hook, around 50-70 words]
"""

    # Step 4: Send to Groq API
    try:
        chat_completion = client.chat.completions.create(
            messages=[{"role": "user", "content": prompt}],
            model=model,
        )
        response_text = chat_completion.choices[0].message.content

        # Extract Narration part (simple regex / split)
        narration = None
        # Use the same robust extraction as in tslTxxYtAcLP
        narration_match = re.search(r"(?:Narration:|Captivating narration for Rank 1:)\s*(.+)", response_text, re.DOTALL | re.IGNORECASE)
        narration = narration_match.group(1).strip() if narration_match else None


        return response_text, news_text, prompt, narration

    except Exception as e:
        return f"Error during Groq API call: {e}", None, None, None


# Call the get_ranked_news function with the news_df and client (called only once now)
response, news_text, prompt, narration = get_ranked_news(news_df, client)

# Print the ranked response
print("--- Groq API Response ---")
print(response)

# Note: The extraction and further processing of narration will happen in the next cell (tslTxxYtAcLP)

--- Groq API Response ---
Rank: 1
Title: This 'impossible' quantum discovery could rewrite the rules of existence
Reasoning: This article discusses a groundbreaking discovery in the field of quantum physics that could challenge our understanding of existence. The concept of an "impossible" phenomenon being observed can spark curiosity and fascination among readers.

Rank: 2
Title: Can humans live under the sea? This live experiment plans to find out
Reasoning: The prospect of humans living underwater is an intriguing idea that combines cutting-edge technology with speculative possibilities. This article highlights an ongoing experiment that could potentially change the way we live and work.

Rank: 3
Title: Human brains emit a seriously weird glow, study finds
Reasoning: This article delves into an unusual aspect of human biology, providing readers with a sense of awe and wonder. The unusual nature of the brain's "glow" sparks curiosity and invites speculation.

Rank: 4
Title: This new experiment could take us closer to a theory of everything
Reasoning: The article explores the concept of a "theory of everything," which is a fundamental idea in physics that has captivated scientists and philosophers for centuries. The mention of an ongoing experiment offers a tangible element of hope and progress.

Rank: 5
Title: There's a new type of acid rain – and scientists are worried
Reasoning: Although this article has some relevance to technology and innovation, it focuses more on environmental concerns than groundbreaking discoveries. Still, it highlights the evolving nature of scientific research and the ongoing battle against environmental challenges.

Rank: 6
Title: After decades of guesswork, science might have found a real hangover hack
Reasoning: This article offers a more lighthearted take on scientific research, presenting a relatively mundane topic as a groundbreaking discovery. While interesting, it doesn't evoke the same level of wonder or awe as the top-ranked articles.

Rank: 7
Title: 5 illusions that reveal how your brain warps reality
Reasoning: This article presents some engaging examples of visual and perceptual illusions, which can be fascinating. However, it's more of a general knowledge piece than a groundbreaking scientific discovery.

Rank: 8
Title: This 'explosive' squirting cucumber can launch seeds at nearly 30mph
Reasoning: While an interesting aspect of plant biology, this article seems more focused on highlighting an unusual natural phenomenon rather than advancing technological innovation or exploring cutting-edge scientific discoveries.

Rank: 9
Title: Mysterious 'surge' under Earth crust could reshape world map, study claims
Reasoning: The article's title seems attention-grabbing, but it doesn't provide an explanation for the nature of the surge or its implications. Without more context, it's difficult to gauge its significance.

Rank: 10
Title: Here’s how to tell if your dog actually loves you, according to science
Reasoning: This article offers helpful advice for dog owners, but it doesn't relate to technology, innovation, or groundbreaking scientific discoveries. It's more of a lifestyle or pet care piece.

---

**Eye-catching Headline:** Groundbreaking Quantum Discovery Shatters Reality

**Captivating Narration:** Imagine a universe where the laws of physics no longer apply. A recent experiment has pushed the boundaries of human knowledge, revealing an "impossible" phenomenon that challenges our understanding of existence. Join us as we explore the mind-bending implications of this quantum revolution and discover the truth about reality.

In [ ]:
import re

# Function to extract Rank 1 Title and Narration from the Groq response text
def extract_rank1_info(response_text):
    # Use a more flexible regex to capture different possible phrasings for Narration
    title_match = re.search(r"Rank: 1\nTitle: (.+)", response_text)
    narration_match = re.search(r"(?:Narration:|Captivating narration for Rank 1:)\s*(.+)", response_text, re.DOTALL | re.IGNORECASE) # Added IGNORECASE

    rank1_title = title_match.group(1).strip() if title_match else None
    rank1_narration = narration_match.group(1).strip() if narration_match else None

    return rank1_title, rank1_narration

# Extract Rank 1 Title and Narration from the response received in the previous cell
# Ensure 'response' variable is available from the execution of the previous cell (Xtxxt3jMACUV)
if 'response' in locals() and response:
    rank1_title, rank1_narration = extract_rank1_info(response)

    # Generate a longer video script if Rank 1 narration was found
    video_script = None
    if rank1_narration:
        script_prompt = f"""
Expand the following narration into an engaging video go direct to the result first and then ery brief about the process etc script that is upto 20 seconds
Important rules:
- Write it as if ONE person is narrating directly to the audience.
- Do NOT include stage directions (like [music], [pause], or "host:").
- Make it conversational and simple, like explaining to a friend.
- Keep it factual and review-style, not dramatic.
- Sentences should be short and clear, suitable for subtitles.
- Focus only on expanding the provided narration text.
- dont use hey there.

Narration: {rank1_narration}
"""

        try:
            chat_completion = client.chat.completions.create(
                messages=[{"role": "user", "content": script_prompt}],
                model="llama-3.1-8b-instant", # Using a suitable model for script generation
            )
            video_script = chat_completion.choices[0].message.content
            print("Final Expanded Video Script:")
            print(video_script)
        except Exception as e:
            print(f"Error generating video script: {e}")
    else:
        print("Could not extract Rank 1 narration to generate video script.")

    # Remove the Rank 1 article from the DataFrame for subsequent calls
    # Ensure 'news_df' variable is available from previous cells
    if 'news_df' in globals() and rank1_title and not news_df.empty:
        # Find the index of the row with the Rank 1 title
        index_to_drop = news_df[news_df['title'] == rank1_title].index

        if not index_to_drop.empty:
            # Drop the row(s) with the matching title
            news_df = news_df.drop(index_to_drop).reset_index(drop=True)
            print(f"\nRemoved '{rank1_title}' from the news DataFrame.")
            print(f"Remaining articles in news_df: {len(news_df)}")
        else:
            print(f"\nCould not find '{rank1_title}' in the current news DataFrame to remove.")
    elif 'news_df' not in globals():
         print("\n'news_df' DataFrame not found. Cannot remove article.")
    else:
        print("\nNo Rank 1 title extracted or news DataFrame is empty, no article removed.")

else:
    print("Response from Groq API not available. Cannot extract Rank 1 info.")


# Display the updated DataFrame head to confirm removal (optional)
# display(news_df.head())

Final Expanded Video Script:
Here's the expanded narration:

**Imagine a universe where the laws of physics no longer apply.**
Our understanding of space and time is about to get turned on its head.
**A recent experiment has pushed the boundaries of human knowledge, revealing an "impossible" phenomenon that challenges our understanding of existence.**
We'll delve into the science behind it, from entanglement to quantum mechanics.
**Join us as we explore the mind-bending implications of this quantum revolution and discover the truth about reality.**
From the smallest particles to the vastness of the cosmos, nothing is as it seems.

**What is this phenomenon and how will it change our world?**
(Brief process: "Join us, discover the truth...")

**Script for subtitles:**
- Universe: no laws apply
- Our understanding of space & time turned on its head
- "Impossible" phenomenon
- Delve into science
- Mind-bending implications
- Truth about reality
- Not as it seems
- Discover the truth, explore the revolution

Could not find 'This 'impossible' quantum discovery could rewrite the rules of existence' in the current news DataFrame to remove.

In [ ]:
# Install edge-tts
%pip install edge-tts

import edge_tts
import asyncio
import nest_asyncio
import os # Import os module

# Apply nest_asyncio to allow running asyncio loops within existing loops
nest_asyncio.apply()

# Define the audio file path
audio_file_path = "video_narration.mp3"

# Delete the existing audio file if it exists
if os.path.exists(audio_file_path):
    os.remove(audio_file_path)
    print(f"Deleted existing audio file: {audio_file_path}")

# Pick the text (script or narration)
audio_text = ""
if 'video_script' in locals() and video_script:
    audio_text = video_script
elif 'narration' in locals() and narration:
    audio_text = narration
else:
    audio_text = "Could not find a script or narration to convert to audio."

# Define the async function for TTS
async def main():
    # Deep male voice
    tts = edge_tts.Communicate(audio_text, voice="en-US-ChristopherNeural", rate="+0%", pitch="-5Hz")
    await tts.save(audio_file_path)

# Run it using the current event loop
loop = asyncio.get_event_loop()
loop.run_until_complete(main())


print(f"Audio saved to {audio_file_path}")

Requirement already satisfied: edge-tts in /usr/local/lib/python3.12/dist-packages (7.2.1)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.0 in /usr/local/lib/python3.12/dist-packages (from edge-tts) (3.12.15)
Requirement already satisfied: certifi>=2023.11.17 in /usr/local/lib/python3.12/dist-packages (from edge-tts) (2025.8.3)
Requirement already satisfied: tabulate<1.0.0,>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from edge-tts) (0.9.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from edge-tts) (4.15.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.0->edge-tts) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.0->edge-tts) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.0->edge-tts) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.0->edge-tts) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.0->edge-tts) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.0->edge-tts) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.0->edge-tts) (1.20.1)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.17.0->aiohttp<4.0.0,>=3.8.0->edge-tts) (3.10)
Deleted existing audio file: video_narration.mp3
Audio saved to video_narration.mp3

# **Stop here dont go below You will face errors**

# Task
Install the necessary libraries, authenticate with the provided Hugging Face token "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", load the Hunyuan AI video generation model from Hugging Face, prepare the previously generated audio and narration text as input, generate a video using the model, and finally display or provide a download link for the generated video.

## Install hugging face libraries

### Subtask:
Install the necessary libraries to interact with the Hugging Face Hub and models.

**Reasoning**:
The first step of the subtask is to install the necessary libraries, starting with `huggingface_hub` and `transformers` using pip.

In [ ]:
%pip install huggingface_hub transformers

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.34.4)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.55.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.1.8)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (2025.8.3)

## Authenticate with hugging face token

### Subtask:
Securely set up your Hugging Face API token to access models.

**Reasoning**:
Import the notebook_login function and authenticate with the provided token.

**Reasoning**:
The previous attempt to use `notebook_login` failed because the `token` argument is not directly accepted. The function is designed to be used in an interactive notebook environment where it will prompt for the token.

In [ ]:
from huggingface_hub import notebook_login

# Call the notebook_login function to authenticate with Hugging Face.
# This will prompt for the token interactively.
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

## Load the hunyuan ai video generation model

### Subtask:
Identify and load the specific Hunyuan AI model for video generation from Hugging Face.

**Reasoning**:
Search the Hugging Face Hub for models related to "Hunyuan" and video generation to identify a suitable model for the task.

In [ ]:
from huggingface_hub import InferenceClient
import os

# Put your Hugging Face token here
os.environ["HF_TOKEN"] = "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" # Ensure this token is valid and has necessary permissions

client = InferenceClient(
    provider="fal-ai",   # Hugging Face partners with fal.ai for this
    token=os.environ["HF_TOKEN"]
)

# Use the generated video_script for the video prompt, if available
# Otherwise, fall back to the original narration or a default prompt
video_prompt = ""
if 'video_script' in locals() and video_script:
    # Construct a more detailed and dynamic prompt from the video script
    video_prompt = f"{video_script}\n\nA cinematic shot, dynamic camera angles, action-oriented, high detail, futuristic, scientific, mysterious, awe-inspiring."
elif 'narration' in locals() and narration:
     video_prompt = f"{narration}\n\nA cinematic shot, dynamic camera angles, action-oriented, high detail, futuristic, scientific, mysterious, awe-inspiring."
else:
    # Fallback prompt if no script or narration is available
    video_prompt = "A dynamic scene depicting a futuristic scientific discovery, cinematic camera angles, action, high detail."


print(f"Using video prompt: {video_prompt}")

# Generate a video using the constructed prompt
# Note: The success of this step depends on the availability and functionality of the 'tencent/HunyuanVideo' model
# via the fal.ai provider and your Hugging Face token's permissions.
try:
    video = client.text_to_video(video_prompt, model="tencent/HunyuanVideo")

    # Save video
    video_file_path = "hunyuan_generated_video.mp4"
    with open(video_file_path, "wb") as f:
        f.write(video)

    print(f"Video saved to {video_file_path}")

except Exception as e:
    print(f"Error generating video: {e}")
    print("Please ensure the 'tencent/HunyuanVideo' model is available via fal.ai and your token is valid.")

**Reasoning**:
Since searching for "Hunyuan video generation" didn't yield results, I will try a broader search for "text-to-video" models on the Hugging Face Hub to find a suitable alternative for video generation.

## Summary:

### Data Analysis Key Findings

* The necessary libraries (`huggingface_hub` and `transformers`) were already installed in the environment.
* Attempting to authenticate with the Hugging Face token directly as a parameter to `notebook_login` failed, as the function requires interactive input. The interactive authentication using `notebook_login()` without arguments was successful.
* Searching for "Hunyuan video generation" models on Hugging Face did not yield any results.
* A broader search for "text-to-video" models identified `ali-vilab/modelscope-damo-text-to-video-synthesis`.
* Loading the identified model using `transformers.AutoModel` failed due to the model type not being recognized by the `transformers` library.
* Attempting to use `modelscope` and `VideoSynthesisPipeline` for the model encountered a `ModuleNotFoundError: No module named 'addict'`, which was resolved by installing the `addict` library.
* A subsequent attempt to load the pipeline with `modelscope` resulted in an `ImportError: cannot import name 'HubDatasetModuleFactoryWithoutScript' from 'datasets.load'`, indicating a dependency conflict between `modelscope` and the installed `datasets` library version, which was not resolved by upgrading `datasets`.

### Insights or Next Steps

* The specific "Hunyuan AI video generation model" requested could not be found on Hugging Face. Further investigation is needed to confirm the correct model name or if it is available on Hugging Face under a different name or organization.
* The dependency conflict between `modelscope` and `datasets` prevented the successful loading of the alternative text-to-video model. Exploring alternative methods for video generation or resolving the library compatibility issue is required for future steps.

In [3]:
!pip install langchain sentence-transformers chromadb

Requirement already satisfied: langchain in /usr/local/lib/python3.13/dist-packages (1.4.3)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.13/dist-packages (5.7.0)
Requirement already satisfied: chromadb in /usr/local/lib/python3.13/dist-packages (1.5.9)
Requirement already satisfied: langchain-core<2.0.0,>=1.6.3 in /usr/local/lib/python3.13/dist-packages (from langchain) (1.6.6)
Requirement already satisfied: langgraph<1.3.0,>=1.2.11 in /usr/local/lib/python3.13/dist-packages (from langchain) (1.2.12)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.13/dist-packages (from langchain) (2.13.5)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (5.18.0)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (0.23.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.33.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.11.0+cu130)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.1.3)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.6.1)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (2.16.0)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.5.1)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.54.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.31.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.42.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.42.1)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.13/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.13/dist-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.84.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (0.27.2)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (37.0.1)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.13/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (5.3.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.13/dist-packages (from chromadb) (3.12.0)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.13/dist-packages (from build>=1.0.3->chromadb) (26.3)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.13/dist-packages (from build>=1.0.3->chromadb) (1.3.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (4.0.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.6.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (2026.6.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.2)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.4)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3<3.0.0,>=2.8.0 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.8.0)
Requirement already satisfied: durationpy>=0.11 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (0.11)
Requirement already satisfied: aiohttp<4.0.0,>=3.14.3 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (3.14.3)
Requirement already satisfied: aiohttp-retry>=2.9.1 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.14.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.17.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.2.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (0.4.5)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.0.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.13/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.13/dist-packages (from onnxruntime>=1.14.1->chromadb) (6.33.6)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.75.5)
Requirement already satisfied: opentelemetry-exporter-otlp-common==0.66b1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (0.66b1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.45.1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-proto==1.45.1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.45.1)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Using cached opentelemetry_sdk-1.45.1-py3-none-any.whl.metadata (1.6 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Using cached opentelemetry_api-1.45.1-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-semantic-conventions==0.66b1 (from opentelemetry-sdk>=1.2.0->chromadb)
  Using cached opentelemetry_semantic_conventions-0.66b1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.4)
Requirement already satisfied: python-dotenv>=1.2.2 in /usr/local/lib/python3.13/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=10.11.0->chromadb) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=10.11.0->chromadb) (2.21.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.7.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.85)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer>=0.9.0->chromadb) (0.0.5)
Requirement already satisfied: httptools>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.8.0)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.23.0)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.3.0)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.25.1)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=1.11.0->sentence-transformers) (1.8.2)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=0.22.0->sentence-transformers) (3.1.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.13/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.6.3->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain) (1.12.2)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.9.0)
Requirement already satisfied: httpx2<3,>=2 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (2.13.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.3.1)

In [4]:
!pip install --force-reinstall google-adk

Collecting google-adk
  Downloading google_adk-2.12.0-py3-none-any.whl.metadata (26 kB)
Collecting aiosqlite>=0.21 (from google-adk)
  Downloading aiosqlite-0.22.1-py3-none-any.whl.metadata (4.3 kB)
Collecting authlib<2,>=1.6.6 (from google-adk)
  Downloading authlib-1.9.1-py2.py3-none-any.whl.metadata (10 kB)
Collecting click<9,>=8.1.8 (from google-adk)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Collecting cryptography>=42 (from google-adk)
  Downloading cryptography-50.0.2-cp311-abi3-manylinux_2_34_x86_64.whl.metadata (4.4 kB)
Collecting fastapi<1,>=0.133 (from google-adk)
  Downloading fastapi-0.143.3-py3-none-any.whl.metadata (26 kB)
Collecting google-auth>=2.47 (from google-auth[pyopenssl]>=2.47->google-adk)
  Downloading google_auth-2.62.0-py3-none-any.whl.metadata (6.0 kB)
Collecting google-genai<3,>=2.30 (from google-adk)
  Downloading google_genai-2.31.0-py3-none-any.whl.metadata (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.6/58.6 kB 6.8 MB/s eta 0:00:00
Collecting graphviz<1,>=0.20.2 (from google-adk)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Collecting httpx<1,>=0.27 (from google-adk)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jsonschema<5,>=4.23 (from google-adk)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting opentelemetry-api<=1.42.1,>=1.39 (from google-adk)
  Using cached opentelemetry_api-1.42.1-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-sdk<=1.42.1,>=1.39 (from google-adk)
  Using cached opentelemetry_sdk-1.42.1-py3-none-any.whl.metadata (1.7 kB)
Collecting packaging>=21 (from google-adk)
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting pydantic<3,>=2.12 (from google-adk)
  Downloading pydantic-2.14.1-py3-none-any.whl.metadata (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.0/133.0 kB 12.1 MB/s eta 0:00:00
Collecting python-dotenv<2,>=1 (from google-adk)
  Downloading python_dotenv-1.2.4-py3-none-any.whl.metadata (29 kB)
Collecting python-multipart<1,>=0.0.9 (from google-adk)
  Downloading python_multipart-0.0.32-py3-none-any.whl.metadata (2.1 kB)
Collecting pyyaml<7,>=6.0.2 (from google-adk)
  Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting requests<3,>=2.32.4 (from google-adk)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting starlette<2,>=1.3.1 (from google-adk)
  Downloading starlette-1.8.0-py3-none-any.whl.metadata (6.6 kB)
Collecting tenacity<10,>=9 (from google-adk)
  Downloading tenacity-9.2.1-py3-none-any.whl.metadata (1.4 kB)
Collecting typing-extensions<5,>=4.5 (from google-adk)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting uvicorn<1,>=0.34 (from google-adk)
  Downloading uvicorn-0.54.0-py3-none-any.whl.metadata (6.6 kB)
Collecting watchdog<7,>=6 (from google-adk)
  Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.3/44.3 kB 5.3 MB/s eta 0:00:00
Collecting websockets<16,>=15.0.1 (from google-adk)
  Downloading websockets-15.0.1-cp313-cp313-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting joserfc>=1.6.8 (from authlib<2,>=1.6.6->google-adk)
  Downloading joserfc-1.7.5-py3-none-any.whl.metadata (3.1 kB)
Collecting cffi>=2.0.0 (from cryptography>=42->google-adk)
  Downloading cffi-2.1.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.5 kB)
Collecting typing-inspection>=0.4.2 (from fastapi<1,>=0.133->google-adk)
  Downloading typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Collecting annotated-doc>=0.0.2 (from fastapi<1,>=0.133->google-adk)
  Downloading annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
INFO: pip is looking at multiple versions of fastapi to determine which version is compatible with other requirements. This could take a while.
Collecting fastapi<1,>=0.133 (from google-adk)
  Downloading fastapi-0.143.2-py3-none-any.whl.metadata (26 kB)
  Downloading fastapi-0.143.1-py3-none-any.whl.metadata (26 kB)
  Downloading fastapi-0.143.0-py3-none-any.whl.metadata (26 kB)
  Downloading fastapi-0.142.4-py3-none-any.whl.metadata (26 kB)
  Downloading fastapi-0.142.3-py3-none-any.whl.metadata (26 kB)
  Downloading fastapi-0.142.2-py3-none-any.whl.metadata (27 kB)
  Downloading fastapi-0.142.1-py3-none-any.whl.metadata (27 kB)
INFO: pip is still looking at multiple versions of fastapi to determine which version is compatible with other requirements. This could take a while.
  Downloading fastapi-0.142.0-py3-none-any.whl.metadata (27 kB)
  Downloading fastapi-0.141.1-py3-none-any.whl.metadata (27 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth>=2.47->google-auth[pyopenssl]>=2.47->google-adk)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting anyio<5.0.0,>=4.8.0 (from google-genai<3,>=2.30->google-adk)
  Downloading anyio-4.15.1-py3-none-any.whl.metadata (4.7 kB)
Collecting tenacity<10,>=9 (from google-adk)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting distro<2,>=1.7.0 (from google-genai<3,>=2.30->google-adk)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting sniffio (from google-genai<3,>=2.30->google-adk)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting certifi (from httpx<1,>=0.27->google-adk)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1,>=0.27->google-adk)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1,>=0.27->google-adk)
  Downloading idna-3.20-py3-none-any.whl.metadata (7.2 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.27->google-adk)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting attrs>=22.2.0 (from jsonschema<5,>=4.23->google-adk)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema<5,>=4.23->google-adk)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema<5,>=4.23->google-adk)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema<5,>=4.23->google-adk)
  Downloading rpds_py-2026.9.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting opentelemetry-semantic-conventions==0.63b1 (from opentelemetry-sdk<=1.42.1,>=1.39->google-adk)
  Using cached opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl.metadata (2.4 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=2.12->google-adk)
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.50.1 (from pydantic<3,>=2.12->google-adk)
  Downloading pydantic_core-2.50.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.5 kB)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.32.4->google-adk)
  Downloading charset_normalizer-3.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 5.0 MB/s eta 0:00:00
Collecting urllib3<3,>=1.26 (from requests<3,>=2.32.4->google-adk)
  Using cached urllib3-2.8.0-py3-none-any.whl.metadata (7.4 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography>=42->google-adk)
  Downloading pycparser-3.11-py3-none-any.whl.metadata (8.2 kB)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth>=2.47->google-auth[pyopenssl]>=2.47->google-adk)
  Downloading pyasn1-0.6.4-py3-none-any.whl.metadata (8.4 kB)
Downloading google_adk-2.12.0-py3-none-any.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 90.6 MB/s eta 0:00:00
Downloading aiosqlite-0.22.1-py3-none-any.whl (17 kB)
Downloading authlib-1.9.1-py2.py3-none-any.whl (266 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 266.0/266.0 kB 31.4 MB/s eta 0:00:00
Downloading click-8.5.0-py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.3/125.3 kB 16.3 MB/s eta 0:00:00
Downloading cryptography-50.0.2-cp311-abi3-manylinux_2_34_x86_64.whl (4.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 100.3 MB/s eta 0:00:00
Downloading fastapi-0.141.1-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.0/132.0 kB 16.4 MB/s eta 0:00:00
Downloading google_auth-2.62.0-py3-none-any.whl (267 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.9/267.9 kB 31.1 MB/s eta 0:00:00
Downloading google_genai-2.31.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 61.1 MB/s eta 0:00:00
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.3/47.3 kB 3.6 MB/s eta 0:00:00
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 9.3 MB/s eta 0:00:00
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 9.6 MB/s eta 0:00:00
Downloading jsonschema-4.26.0-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 kB 11.3 MB/s eta 0:00:00
Using cached opentelemetry_api-1.42.1-py3-none-any.whl (61 kB)
Using cached opentelemetry_sdk-1.42.1-py3-none-any.whl (170 kB)
Using cached opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl (203 kB)
Downloading packaging-26.3-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.0/130.0 kB 16.2 MB/s eta 0:00:00
Downloading pydantic-2.14.1-py3-none-any.whl (488 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.1/488.1 kB 47.5 MB/s eta 0:00:00
Downloading pydantic_core-2.50.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 84.3 MB/s eta 0:00:00
Downloading python_dotenv-1.2.4-py3-none-any.whl (23 kB)
Downloading python_multipart-0.0.32-py3-none-any.whl (30 kB)
Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.6/801.6 kB 56.1 MB/s eta 0:00:00
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 8.1 MB/s eta 0:00:00
Downloading starlette-1.8.0-py3-none-any.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.6/79.6 kB 10.3 MB/s eta 0:00:00
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 5.3 MB/s eta 0:00:00
Downloading uvicorn-0.54.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.4/87.4 kB 11.0 MB/s eta 0:00:00
Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 9.2 MB/s eta 0:00:00
Downloading websockets-15.0.1-cp313-cp313-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (182 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.5/182.5 kB 21.5 MB/s eta 0:00:00
Downloading annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Downloading anyio-4.15.1-py3-none-any.whl (132 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.1/132.1 kB 15.3 MB/s eta 0:00:00
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.5/67.5 kB 8.2 MB/s eta 0:00:00
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.0/137.0 kB 16.3 MB/s eta 0:00:00
Downloading cffi-2.1.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (221 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 221.8/221.8 kB 24.1 MB/s eta 0:00:00
Downloading charset_normalizer-3.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (254 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 254.7/254.7 kB 24.2 MB/s eta 0:00:00
Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading idna-3.20-py3-none-any.whl (69 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.6/69.6 kB 8.3 MB/s eta 0:00:00
Downloading joserfc-1.7.5-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.3/71.3 kB 8.7 MB/s eta 0:00:00
Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.3/181.3 kB 21.7 MB/s eta 0:00:00
Downloading referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rpds_py-2026.9.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (370 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 370.8/370.8 kB 39.4 MB/s eta 0:00:00
Downloading typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Using cached urllib3-2.8.0-py3-none-any.whl (135 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading pyasn1-0.6.4-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.4/84.4 kB 9.8 MB/s eta 0:00:00
Downloading pycparser-3.11-py3-none-any.whl (51 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.2/51.2 kB 6.5 MB/s eta 0:00:00
Installing collected packages: websockets, watchdog, urllib3, typing-extensions, tenacity, sniffio, rpds-py, pyyaml, python-multipart, python-dotenv, pycparser, pyasn1, packaging, idna, h11, graphviz, distro, click, charset_normalizer, certifi, attrs, annotated-types, annotated-doc, aiosqlite, uvicorn, typing-inspection, requests, referencing, pydantic-core, pyasn1-modules, opentelemetry-api, httpcore, cffi, anyio, starlette, pydantic, opentelemetry-semantic-conventions, jsonschema-specifications, httpx, cryptography, opentelemetry-sdk, jsonschema, joserfc, google-auth, fastapi, authlib, google-genai, google-adk
  Attempting uninstall: websockets
    Found existing installation: websockets 15.0.1
    Uninstalling websockets-15.0.1:
      Successfully uninstalled websockets-15.0.1
  Attempting uninstall: watchdog
    Found existing installation: watchdog 6.0.0
    Uninstalling watchdog-6.0.0:
      Successfully uninstalled watchdog-6.0.0
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.8.0
    Uninstalling urllib3-2.8.0:
      Successfully uninstalled urllib3-2.8.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.16.0
    Uninstalling typing_extensions-4.16.0:
      Successfully uninstalled typing_extensions-4.16.0
  Attempting uninstall: tenacity
    Found existing installation: tenacity 9.1.4
    Uninstalling tenacity-9.1.4:
      Successfully uninstalled tenacity-9.1.4
  Attempting uninstall: sniffio
    Found existing installation: sniffio 1.3.1
    Uninstalling sniffio-1.3.1:
      Successfully uninstalled sniffio-1.3.1
  Attempting uninstall: rpds-py
    Found existing installation: rpds-py 2026.6.3
    Uninstalling rpds-py-2026.6.3:
      Successfully uninstalled rpds-py-2026.6.3
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
  Attempting uninstall: python-multipart
    Found existing installation: python-multipart 0.0.32
    Uninstalling python-multipart-0.0.32:
      Successfully uninstalled python-multipart-0.0.32
  Attempting uninstall: python-dotenv
    Found existing installation: python-dotenv 1.2.3
    Uninstalling python-dotenv-1.2.3:
      Successfully uninstalled python-dotenv-1.2.3
  Attempting uninstall: pycparser
    Found existing installation: pycparser 3.0
    Uninstalling pycparser-3.0:
      Successfully uninstalled pycparser-3.0
  Attempting uninstall: pyasn1
    Found existing installation: pyasn1 0.6.4
    Uninstalling pyasn1-0.6.4:
      Successfully uninstalled pyasn1-0.6.4
  Attempting uninstall: packaging
    Found existing installation: packaging 26.3
    Uninstalling packaging-26.3:
      Successfully uninstalled packaging-26.3
  Attempting uninstall: idna
    Found existing installation: idna 3.20
    Uninstalling idna-3.20:
      Successfully uninstalled idna-3.20
  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
      Successfully uninstalled h11-0.16.0
  Attempting uninstall: graphviz
    Found existing installation: graphviz 0.21
    Uninstalling graphviz-0.21:
      Successfully uninstalled graphviz-0.21
  Attempting uninstall: distro
    Found existing installation: distro 1.9.0
    Uninstalling distro-1.9.0:
      Successfully uninstalled distro-1.9.0
  Attempting uninstall: click
    Found existing installation: click 8.5.0
    Uninstalling click-8.5.0:
      Successfully uninstalled click-8.5.0
  Attempting uninstall: charset_normalizer
    Found existing installation: charset-normalizer 3.4.9
    Uninstalling charset-normalizer-3.4.9:
      Successfully uninstalled charset-normalizer-3.4.9
  Attempting uninstall: certifi
    Found existing installation: certifi 2026.7.22
    Uninstalling certifi-2026.7.22:
      Successfully uninstalled certifi-2026.7.22
  Attempting uninstall: attrs
    Found existing installation: attrs 26.1.0
    Uninstalling attrs-26.1.0:
      Successfully uninstalled attrs-26.1.0
  Attempting uninstall: annotated-types
    Found existing installation: annotated-types 0.8.0
    Uninstalling annotated-types-0.8.0:
      Successfully uninstalled annotated-types-0.8.0
  Attempting uninstall: annotated-doc
    Found existing installation: annotated-doc 0.0.5
    Uninstalling annotated-doc-0.0.5:
      Successfully uninstalled annotated-doc-0.0.5
  Attempting uninstall: aiosqlite
    Found existing installation: aiosqlite 0.22.1
    Uninstalling aiosqlite-0.22.1:
      Successfully uninstalled aiosqlite-0.22.1
  Attempting uninstall: uvicorn
    Found existing installation: uvicorn 0.54.0
    Uninstalling uvicorn-0.54.0:
      Successfully uninstalled uvicorn-0.54.0
  Attempting uninstall: typing-inspection
    Found existing installation: typing-inspection 0.4.4
    Uninstalling typing-inspection-0.4.4:
      Successfully uninstalled typing-inspection-0.4.4
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: referencing
    Found existing installation: referencing 0.37.0
    Uninstalling referencing-0.37.0:
      Successfully uninstalled referencing-0.37.0
  Attempting uninstall: pydantic-core
    Found existing installation: pydantic_core 2.46.5
    Uninstalling pydantic_core-2.46.5:
      Successfully uninstalled pydantic_core-2.46.5
  Attempting uninstall: pyasn1-modules
    Found existing installation: pyasn1_modules 0.4.2
    Uninstalling pyasn1_modules-0.4.2:
      Successfully uninstalled pyasn1_modules-0.4.2
  Attempting uninstall: opentelemetry-api
    Found existing installation: opentelemetry-api 1.45.1
    Uninstalling opentelemetry-api-1.45.1:
      Successfully uninstalled opentelemetry-api-1.45.1
  Attempting uninstall: httpcore
    Found existing installation: httpcore 1.0.9
    Uninstalling httpcore-1.0.9:
      Successfully uninstalled httpcore-1.0.9
  Attempting uninstall: cffi
    Found existing installation: cffi 2.1.1
    Uninstalling cffi-2.1.1:
      Successfully uninstalled cffi-2.1.1
  Attempting uninstall: anyio
    Found existing installation: anyio 4.15.1
    Uninstalling anyio-4.15.1:
      Successfully uninstalled anyio-4.15.1
  Attempting uninstall: starlette
    Found existing installation: starlette 1.7.0
    Uninstalling starlette-1.7.0:
      Successfully uninstalled starlette-1.7.0
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.13.5
    Uninstalling pydantic-2.13.5:

In [2]:
!pip install "opentelemetry-api==1.42.1" "opentelemetry-sdk==1.42.1"

Collecting opentelemetry-api==1.42.1
  Downloading opentelemetry_api-1.42.1-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-sdk==1.42.1
  Downloading opentelemetry_sdk-1.42.1-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-api==1.42.1) (4.16.0)
Collecting opentelemetry-semantic-conventions==0.63b1 (from opentelemetry-sdk==1.42.1)
  Downloading opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl.metadata (2.4 kB)
Downloading opentelemetry_api-1.42.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 2.9 MB/s eta 0:00:00
Downloading opentelemetry_sdk-1.42.1-py3-none-any.whl (170 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 10.3 MB/s eta 0:00:00
Downloading opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl (203 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 21.5 MB/s eta 0:00:00
Installing collected packages: opentelemetry-api, opentelemetry-semantic-conventions, opentelemetry-sdk
  Attempting uninstall: opentelemetry-api
    Found existing installation: opentelemetry-api 1.45.1
    Uninstalling opentelemetry-api-1.45.1:
      Successfully uninstalled opentelemetry-api-1.45.1
  Attempting uninstall: opentelemetry-semantic-conventions
    Found existing installation: opentelemetry-semantic-conventions 0.66b1
    Uninstalling opentelemetry-semantic-conventions-0.66b1:
      Successfully uninstalled opentelemetry-semantic-conventions-0.66b1
  Attempting uninstall: opentelemetry-sdk
    Found existing installation: opentelemetry-sdk 1.45.1
    Uninstalling opentelemetry-sdk-1.45.1:
      Successfully uninstalled opentelemetry-sdk-1.45.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-exporter-otlp-common 0.66b1 requires opentelemetry-sdk~=1.45.1, but you have opentelemetry-sdk 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-grpc 1.45.1 requires opentelemetry-sdk~=1.45.1, but you have opentelemetry-sdk 1.42.1 which is incompatible.
Successfully installed opentelemetry-api-1.42.1 opentelemetry-sdk-1.42.1 opentelemetry-semantic-conventions-0.63b1

In [ ]:
from langchain.text_splitter import RecursiveCharacterTextSplitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)
chunks = text_splitter.split_text(your_large_document_text)
print(f"Total chunks created: {len(chunks)}")

In [1]:
!pip install langchain sentence-transformers chromadb

Requirement already satisfied: langchain in /usr/local/lib/python3.13/dist-packages (1.4.3)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.13/dist-packages (5.7.0)
Requirement already satisfied: chromadb in /usr/local/lib/python3.13/dist-packages (1.5.9)
Requirement already satisfied: langchain-core<2.0.0,>=1.6.3 in /usr/local/lib/python3.13/dist-packages (from langchain) (1.6.6)
Requirement already satisfied: langgraph<1.3.0,>=1.2.11 in /usr/local/lib/python3.13/dist-packages (from langchain) (1.2.12)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.13/dist-packages (from langchain) (2.14.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (5.18.0)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (0.23.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.33.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.11.0+cu130)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.1.3)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.6.1)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (2.16.0)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.5.1)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.54.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.31.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.42.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.42.1)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.13/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.13/dist-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.84.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (0.27.2)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (37.0.1)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.13/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (5.3.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.13/dist-packages (from chromadb) (3.12.0)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.13/dist-packages (from build>=1.0.3->chromadb) (26.3)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.13/dist-packages (from build>=1.0.3->chromadb) (1.3.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (4.0.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.6.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (2026.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.2)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.34.2)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3<3.0.0,>=2.8.0 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.8.0)
Requirement already satisfied: durationpy>=0.11 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (0.11)
Requirement already satisfied: aiohttp<4.0.0,>=3.14.3 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (3.14.3)
Requirement already satisfied: aiohttp-retry>=2.9.1 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.14.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.17.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.2.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (0.4.5)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.0.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.13/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.13/dist-packages (from onnxruntime>=1.14.1->chromadb) (6.33.6)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.75.5)
Requirement already satisfied: opentelemetry-exporter-otlp-common==0.66b1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (0.66b1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.45.1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-proto==1.45.1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.45.1)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Using cached opentelemetry_sdk-1.45.1-py3-none-any.whl.metadata (1.6 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Using cached opentelemetry_api-1.45.1-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-semantic-conventions==0.66b1 (from opentelemetry-sdk>=1.2.0->chromadb)
  Using cached opentelemetry_semantic_conventions-0.66b1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.50.1)
Requirement already satisfied: typing-inspection>=0.4.4 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.4)
Requirement already satisfied: python-dotenv>=1.2.2 in /usr/local/lib/python3.13/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=10.11.0->chromadb) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=10.11.0->chromadb) (2.21.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.7.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.85)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer>=0.9.0->chromadb) (0.0.5)
Requirement already satisfied: httptools>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.8.0)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.23.0)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.3.0)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.25.1)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=1.11.0->sentence-transformers) (1.8.2)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=0.22.0->sentence-transformers) (3.1.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.13/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.6.3->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain) (1.12.2)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.9.0)
Requirement already satisfied: httpx2<3,>=2 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (2.13.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.3.1)

In [3]:
!pip install langchain langchain-text-splitters sentence-transformers chromadb

Requirement already satisfied: langchain in /usr/local/lib/python3.13/dist-packages (1.4.3)
Collecting langchain-text-splitters
  Downloading langchain_text_splitters-1.1.3-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.13/dist-packages (5.7.0)
Requirement already satisfied: chromadb in /usr/local/lib/python3.13/dist-packages (1.5.9)
Requirement already satisfied: langchain-core<2.0.0,>=1.6.3 in /usr/local/lib/python3.13/dist-packages (from langchain) (1.6.6)
Requirement already satisfied: langgraph<1.3.0,>=1.2.11 in /usr/local/lib/python3.13/dist-packages (from langchain) (1.2.12)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.13/dist-packages (from langchain) (2.14.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (5.18.0)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (0.23.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.33.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.11.0+cu130)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.1.3)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.6.1)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (2.16.0)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.5.1)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.54.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.31.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.45.1)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.13/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.13/dist-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.84.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (0.27.2)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (37.0.1)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.13/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (5.3.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.13/dist-packages (from chromadb) (3.12.0)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.13/dist-packages (from build>=1.0.3->chromadb) (26.3)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.13/dist-packages (from build>=1.0.3->chromadb) (1.3.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (4.0.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.6.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (2026.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.2)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.34.2)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3<3.0.0,>=2.8.0 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.8.0)
Requirement already satisfied: durationpy>=0.11 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (0.11)
Requirement already satisfied: aiohttp<4.0.0,>=3.14.3 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (3.14.3)
Requirement already satisfied: aiohttp-retry>=2.9.1 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.14.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.17.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.2.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (0.4.5)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.0.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.13/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.13/dist-packages (from onnxruntime>=1.14.1->chromadb) (6.33.6)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.75.5)
Requirement already satisfied: opentelemetry-exporter-otlp-common==0.66b1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (0.66b1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.45.1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-proto==1.45.1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-semantic-conventions==0.66b1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.66b1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.50.1)
Requirement already satisfied: typing-inspection>=0.4.4 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.4)
Requirement already satisfied: python-dotenv>=1.2.2 in /usr/local/lib/python3.13/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=10.11.0->chromadb) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=10.11.0->chromadb) (2.21.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.7.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.85)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer>=0.9.0->chromadb) (0.0.5)
Requirement already satisfied: httptools>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.8.0)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.23.0)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.3.0)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.25.1)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=1.11.0->sentence-transformers) (1.8.2)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=0.22.0->sentence-transformers) (3.1.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.13/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.6.3->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain) (1.12.2)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.9.0)
Requirement already satisfied: httpx2<3,>=2 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (2.13.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.3.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (0.25.0)

In [5]:
import sys
!{sys.executable} -m pip install langchain langchain-text-splitters sentence-transformers chromadb

Requirement already satisfied: langchain in /usr/local/lib/python3.13/dist-packages (1.4.3)
Requirement already satisfied: langchain-text-splitters in /usr/local/lib/python3.13/dist-packages (1.1.3)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.13/dist-packages (5.7.0)
Requirement already satisfied: chromadb in /usr/local/lib/python3.13/dist-packages (1.5.9)
Requirement already satisfied: langchain-core<2.0.0,>=1.6.3 in /usr/local/lib/python3.13/dist-packages (from langchain) (1.6.6)
Requirement already satisfied: langgraph<1.3.0,>=1.2.11 in /usr/local/lib/python3.13/dist-packages (from langchain) (1.2.12)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.13/dist-packages (from langchain) (2.14.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (5.18.0)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (0.23.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.33.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.11.0+cu130)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.1.3)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.6.1)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (2.16.0)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.5.1)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.54.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.31.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.45.1)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.13/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.13/dist-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (1.84.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (0.27.2)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (37.0.1)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.13/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from chromadb) (5.3.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.13/dist-packages (from chromadb) (3.12.0)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.13/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.13/dist-packages (from build>=1.0.3->chromadb) (26.3)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.13/dist-packages (from build>=1.0.3->chromadb) (1.3.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27.0->chromadb) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (4.0.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.6.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=4.19.0->chromadb) (2026.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.2)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.34.2)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3<3.0.0,>=2.8.0 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.8.0)
Requirement already satisfied: durationpy>=0.11 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (0.11)
Requirement already satisfied: aiohttp<4.0.0,>=3.14.3 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (3.14.3)
Requirement already satisfied: aiohttp-retry>=2.9.1 in /usr/local/lib/python3.13/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.14.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.17.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.2.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (0.4.5)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.0.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.13/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.13/dist-packages (from onnxruntime>=1.14.1->chromadb) (6.33.6)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.75.5)
Requirement already satisfied: opentelemetry-exporter-otlp-common==0.66b1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (0.66b1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.45.1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-proto==1.45.1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-semantic-conventions==0.66b1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.66b1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.50.1)
Requirement already satisfied: typing-inspection>=0.4.4 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.4)
Requirement already satisfied: python-dotenv>=1.2.2 in /usr/local/lib/python3.13/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=10.11.0->chromadb) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=10.11.0->chromadb) (2.21.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.7.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (13.0.85)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer>=0.9.0->chromadb) (0.0.5)
Requirement already satisfied: httptools>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.8.0)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.23.0)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.3.0)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.25.1)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=1.11.0->sentence-transformers) (1.8.2)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=0.22.0->sentence-transformers) (3.1.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.13/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.6.3->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain) (1.12.2)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.9.0)
Requirement already satisfied: httpx2<3,>=2 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (2.13.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.3.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (0.25.0)

In [6]:
import time
import uuid
import chromadb
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer
def chunk_text(text: str, chunk_size: int = 300, chunk_overlap: int = 50) -> list:
    """
    Edge Case Handled: Empty or whitespace-only documents return an empty list.
    """
    if not text or not text.strip():
        return []
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap
    )
    return splitter.split_text(text)
def test_chunking_strategy():
    """Unit test to verify that chunking splits text correctly and handles edge cases."""
    # Test case 1: Normal text splitting
    sample_large_text = "Retrieval-Augmented Generation (RAG) is amazing. " * 20
    chunks = chunk_text(sample_large_text, chunk_size=200, chunk_overlap=30)
    assert len(chunks) > 1, "Failed: Text was not split into multiple chunks."
    empty_chunks = chunk_text("")
    assert empty_chunks == [], "Failed: Empty text handling failed."
    print("✅ Unit Test Passed: Chunking strategy and edge cases work successfully!\n")
test_chunking_strategy()
sample_documents = [
    "Retrieval-Augmented Generation (RAG) combines LLMs with external knowledge bases to improve factual accuracy.",
    "RecursiveCharacterTextSplitter splits text based on a list of separators (like paragraphs, newlines, and spaces) to keep semantic context intact.",
    "ChromaDB is a lightweight vector database designed to store embeddings and perform fast semantic search queries.",
    "Sentence-transformers allow converting text sentences into dense vector representations for machine learning applications."
]
all_chunks = []
for doc in sample_documents:
    all_chunks.extend(chunk_text(doc, chunk_size=150, chunk_overlap=20))
print(f"Total chunks generated: {len(all_chunks)}")
print("--- Generating Embeddings ---")
start_embed_time = time.time()
model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(all_chunks)
end_embed_time = time.time()
embedding_duration = end_embed_time - start_embed_time
print(f"⏱️ Embedding Generation Time: {embedding_duration:.4f} seconds for {len(all_chunks)} chunks.\n")
client = chromadb.Client()
collection_name = "assignment_rag_collection"
try:
    client.delete_collection(collection_name)
except Exception:
    pass
collection = client.create_collection(name=collection_name)
chunk_ids = [str(uuid.uuid4()) for _ in all_chunks]
collection.add(
    documents=all_chunks,
    embeddings=embeddings.tolist(),
    ids=chunk_ids
)
print("✅ Data successfully ingested into ChromaDB with unique IDs and clean state.\n")
test_queries = [
    "What is RAG?",
    "How does ChromaDB work?",
    "Why use recursive character text splitter?"
]
print("--- Retrieval Performance & Latency Testing Script ---")
for query in test_queries:
    start_search = time.time()

    results = collection.query(
        query_texts=[query],
        n_results=2
    )
    end_search = time.time()
    latency_ms = (end_search - start_search) * 1000
    print(f"Query: '{query}'")
    print(f"⏱️ Search Latency: {latency_ms:.2f} ms")
    print(f"Top Result Match: {results['documents'][0][0][:100]}...\n")

✅ Unit Test Passed: Chunking strategy and edge cases work successfully!

Total chunks generated: 4
--- Generating Embeddings ---

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

⏱️ Embedding Generation Time: 7.4098 seconds for 4 chunks.

✅ Data successfully ingested into ChromaDB with unique IDs and clean state.

--- Retrieval Performance & Latency Testing Script ---

/root/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx.tar.gz: 100%|██████████| 79.3M/79.3M [00:03<00:00, 26.7MiB/s]

Query: 'What is RAG?'
⏱️ Search Latency: 4742.84 ms
Top Result Match: Retrieval-Augmented Generation (RAG) combines LLMs with external knowledge bases to improve factual ...

Query: 'How does ChromaDB work?'
⏱️ Search Latency: 295.49 ms
Top Result Match: ChromaDB is a lightweight vector database designed to store embeddings and perform fast semantic sea...

Query: 'Why use recursive character text splitter?'
⏱️ Search Latency: 306.24 ms
Top Result Match: RecursiveCharacterTextSplitter splits text based on a list of separators (like paragraphs, newlines,...